### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jon4hz** [charmbracelet/wishlist#112] opened 2022-08-29 21:58 UTC
I've noticed some very high CPU usage when using wishlist as a library. Unfortunately I can't reproduce it or add much debug context, but I noticed, that I had +500% CPU usage sometimes with a lot of wishlist (wishbox to be precise) processes running even though, I had no active session at that moment.

**Comment by caarlos0** [comment] 2024-02-29 15:25
I was a 100% sure I had replied to this, seems like I didn't, sorry.

Anyway, I did tried to reproduce this, and couldn't.

Since no one else reported it, and wishlist changed a lot since this was opened, I think I'm going to close it.

Feel free to re-open if it still happens or if you have more details!

Thanks

**Closed by caarlos0** 2024-02-29 15:25 UTC

**Comment by ozeliurs** [comment] 2024-07-06 13:36
Hi,

I have the same issue on my box, the VM I am using has 2 cores and wishlist eats nearly all of it (180% of 200%).

I link the logs from the app, the output of ps -aux and a screen of htop. If you need anything else, I would be glad to give it to you.

Hoping this will resolve this problem.

<img width="1464" alt="Capture d’écran 2024-07-06 à 20 32 19" src="https://github.com/charmbracelet/wishlist/assets/59318604/19f8fc4e-a733-450e-bac6-8815acd86c89">

[logs.txt](https://github.com/user-attachments/files/16116295/logs.txt)
[ps.txt](https://github.com/user-attachments/files/16116296/ps.txt)
